name: CI validation
on:
  push:
    branches: [ 'master', 'image_in_cell_table' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore NPM dependencies
        run: npm ci

      - name: Test
        run: npm test
